# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrecap < Formula
  desc "Know what you actually did today, including your AI sessions"
  homepage "https://github.com/cloudprobe/devrecap"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.1.2/devrecap_0.1.2_darwin_amd64.tar.gz"
      sha256 "af728a5fff8972ce0ed021c469ce196b1d3616943c7148919c0a92c394468933"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.1.2/devrecap_0.1.2_darwin_arm64.tar.gz"
      sha256 "1c98f9b9b22ee749f512e54d1fbb33e98c281eb16413553087d6fff17aba44dd"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.1.2/devrecap_0.1.2_linux_amd64.tar.gz"
      sha256 "22ceb6ac35e3f0c156eb708798f708cb47d01a8163ec8361c96761e6d710a9a9"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.1.2/devrecap_0.1.2_linux_arm64.tar.gz"
      sha256 "f9298c4abd70ed24eca393577bb9be3dbe0919a670dfdd7f60e58b4e432f4701"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  test do
    assert_match "devrecap", shell_output("#{bin}/devrecap --version")
  end
end
