# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrecap < Formula
  desc "Know what you actually did today, including your AI sessions"
  homepage "https://github.com/cloudprobe/devrecap"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.0/devrecap_0.2.0_darwin_amd64.tar.gz"
      sha256 "a2b8873dfd5286b42a8d3d18ed7ad44e47363ac5cdf73cdfbbc3c2dc79fa79a7"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.0/devrecap_0.2.0_darwin_arm64.tar.gz"
      sha256 "0e249bb65f1fb17bffbf90ef44a4ad1ac7ae45d43bcd025d0983ad76269d90cd"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.0/devrecap_0.2.0_linux_amd64.tar.gz"
      sha256 "5c2ccc12840658f3acd9a8b3ffd807463285e54ddfdbb6e88b5809ff298491ab"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.0/devrecap_0.2.0_linux_arm64.tar.gz"
      sha256 "7dd47b1e85e33f62aaa233a17e55a2d8f9eec10c7223404363e9396282e7aa1c"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  test do
    assert_match "devrecap", shell_output("#{bin}/devrecap --version")
  end
end
