# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debrief < Formula
  desc "Know what you actually did today — git commits, AI sessions, one command"
  homepage "https://github.com/cloudprobe/debrief"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.3/debrief_0.6.3_darwin_amd64.tar.gz"
      sha256 "4b48e270fcc6513603a0338ff7a605262ebc84fbe15ebc2ed9dcc7d4d8bb55c4"

      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.3/debrief_0.6.3_darwin_arm64.tar.gz"
      sha256 "bce4d5f15723b281a836ff9c362ab1d26e91c3bac5727bd4fbff3109f0c2cf2a"

      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.3/debrief_0.6.3_linux_amd64.tar.gz"
      sha256 "ea9ce8c6544a662ede253287ec41a2af25de84805596167d3f894f9b0919fb95"
      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.3/debrief_0.6.3_linux_arm64.tar.gz"
      sha256 "75060e18419497cbae442afd00af971c9bbf4c274e0224a284b9057576c65528"
      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  test do
    assert_match "debrief", shell_output("#{bin}/debrief --version")
  end
end
