# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debrief < Formula
  desc "Know what you actually did today — git commits, AI sessions, one command"
  homepage "https://github.com/cloudprobe/debrief"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.8.1/debrief_0.8.1_darwin_amd64.tar.gz"
      sha256 "5c7db686f4e56202d2dafcd0d30227d733e98b0cfb5ebee051ac962f7212b862"

      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.8.1/debrief_0.8.1_darwin_arm64.tar.gz"
      sha256 "9ca9ff8ec5488be50942863f7c44bfe8ec982b7cd3d796d9d74c042ebb203f2d"

      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.8.1/debrief_0.8.1_linux_amd64.tar.gz"
      sha256 "69406d58a368718d48be2f65ea4427b5b0dd4eb50c86cdbb4d3860978ade250a"
      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.8.1/debrief_0.8.1_linux_arm64.tar.gz"
      sha256 "7d4957ca83b749373b4c77e2052ae945a2f3f2b1928454e909d67f1170856dcb"
      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  test do
    assert_match "debrief", shell_output("#{bin}/debrief --version")
  end
end
