# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Debrief < Formula
  desc "Know what you actually did today — git commits, AI sessions, one command"
  homepage "https://github.com/cloudprobe/debrief"
  version "0.6.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.7/debrief_0.6.7_darwin_amd64.tar.gz"
      sha256 "1a86713d65dee14b53469aac514678a4ec935e70d29a5a8a2621d536d3c87a58"

      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.7/debrief_0.6.7_darwin_arm64.tar.gz"
      sha256 "d0badeebdd72624b58357bc7c20d7ac4443a1f45265a35e22e8a6b461ab0154d"

      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.7/debrief_0.6.7_linux_amd64.tar.gz"
      sha256 "d92f0c1f8271671485c6d3a8a87b5bf1a8f50beaad09e893eb040d55d4f07ed5"
      define_method(:install) do
        bin.install "debrief"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/debrief/releases/download/v0.6.7/debrief_0.6.7_linux_arm64.tar.gz"
      sha256 "d57ce73c08cfa5697dcb60242973a264cea1b11d8417fe231023d7d8bd88f8ea"
      define_method(:install) do
        bin.install "debrief"
      end
    end
  end

  test do
    assert_match "debrief", shell_output("#{bin}/debrief --version")
  end
end
