# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrecap < Formula
  desc "Know what you actually did today, including your AI sessions"
  homepage "https://github.com/cloudprobe/devrecap"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.3.1/devrecap_0.3.1_darwin_amd64.tar.gz"
      sha256 "d6d7d65b54c00f7a4273ccec3bfb0898bdaedabc98a7f0661a761de0dd5958e6"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.3.1/devrecap_0.3.1_darwin_arm64.tar.gz"
      sha256 "4151e3cf42cef8e7de88cc7787a8d0c41b9c3260c9265824dbe8d55c7184f532"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.3.1/devrecap_0.3.1_linux_amd64.tar.gz"
      sha256 "91d1cb3356e3a4b2fe29eaa1a9b2e2fae5389711aa2d82055e5fbe88203c94ea"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.3.1/devrecap_0.3.1_linux_arm64.tar.gz"
      sha256 "51b7400ac4b3a1e9e2433f37f999c566cbf98903548a92e3c7c2d273772dafb4"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  test do
    assert_match "devrecap", shell_output("#{bin}/devrecap --version")
  end
end
