# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrecap < Formula
  desc "Know what you actually did today, including your AI sessions"
  homepage "https://github.com/cloudprobe/devrecap"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.1/devrecap_0.2.1_darwin_amd64.tar.gz"
      sha256 "2aeeaa01e44845cc8c83b0e361658faa10bd6694dd73bebbc409522bb658e47a"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.1/devrecap_0.2.1_darwin_arm64.tar.gz"
      sha256 "a6796a9ddc443ecbe02eb4f638203d6983156c12ab37417274f944f26839899a"

      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.1/devrecap_0.2.1_linux_amd64.tar.gz"
      sha256 "413228632eaf07e2ab0955c237d5da87b5976b8fc497173db67d9df50653ac4e"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudprobe/devrecap/releases/download/v0.2.1/devrecap_0.2.1_linux_arm64.tar.gz"
      sha256 "bad903eaf17793a34048afb58befe97bd7882b334965b268d42d5427a3f0b78c"
      define_method(:install) do
        bin.install "devrecap"
      end
    end
  end

  test do
    assert_match "devrecap", shell_output("#{bin}/devrecap --version")
  end
end
